# Form implementation generated from reading ui file 'passwordgen.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 575)
        MainWindow.setMinimumSize(QtCore.QSize(480, 575))
        MainWindow.setMaximumSize(QtCore.QSize(480, 575))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_main = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_main.setGeometry(QtCore.QRect(160, 10, 161, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(32)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.title_main.setFont(font)
        self.title_main.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.title_main.setObjectName("title_main")
        self.label_sym = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_sym.setGeometry(QtCore.QRect(10, 170, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_sym.setFont(font)
        self.label_sym.setObjectName("label_sym")
        self.label_cap = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cap.setGeometry(QtCore.QRect(10, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_cap.setFont(font)
        self.label_cap.setObjectName("label_cap")
        self.label_num = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_num.setGeometry(QtCore.QRect(10, 230, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_num.setFont(font)
        self.label_num.setObjectName("label_num")
        self.title_pass = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_pass.setGeometry(QtCore.QRect(110, 380, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.title_pass.setFont(font)
        self.title_pass.setObjectName("title_pass")
        self.label_pass = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_pass.setGeometry(QtCore.QRect(30, 460, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_pass.setFont(font)
        self.label_pass.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_pass.setObjectName("label_pass")
        self.button_generate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_generate.setGeometry(QtCore.QRect(180, 310, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_generate.setFont(font)
        self.button_generate.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);\n"
"\n"
"\n"
"")
        self.button_generate.setObjectName("button_generate")
        self.text_cap = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_cap.setGeometry(QtCore.QRect(360, 100, 61, 31))
        self.text_cap.setObjectName("text_cap")
        self.text_sym = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_sym.setGeometry(QtCore.QRect(360, 170, 61, 31))
        self.text_sym.setObjectName("text_sym")
        self.text_num = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_num.setGeometry(QtCore.QRect(360, 240, 61, 31))
        self.text_num.setObjectName("text_num")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Generator"))
        self.title_main.setText(_translate("MainWindow", "PassGen"))
        self.label_sym.setText(_translate("MainWindow", "Number of Symbols:"))
        self.label_cap.setText(_translate("MainWindow", "Number of Capital Letters:"))
        self.label_num.setText(_translate("MainWindow", "Number of Numbers:"))
        self.title_pass.setText(_translate("MainWindow", "Generated Password:"))
        self.label_pass.setText(_translate("MainWindow", "Password"))
        self.button_generate.setText(_translate("MainWindow", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
